import type { AnalysisResult, TechItem } from '@/types'
import { CATEGORY_PALETTE } from './tech-detector'

// ─── Badge Generators ─────────────────────────────────────────────────────────

const BADGE_COLORS: Record<string, string> = {
  language:   '7c3aed',
  framework:  '2563eb',
  ui:         'db2777',
  database:   '059669',
  tooling:    'd97706',
  deployment: '0891b2',
  testing:    'e11d48',
  state:      'ea580c',
}

function makeBadge(tech: TechItem): string {
  const color = BADGE_COLORS[tech.category] ?? '6b7280'
  const label = encodeURIComponent(tech.name)
  return `![${tech.name}](https://img.shields.io/badge/${label}-${color}?style=flat-square&logo=${encodeURIComponent(tech.name.toLowerCase().replace(/\s/g, ''))}&logoColor=white)`
}

function groupBadges(techStack: TechItem[]): string {
  const groups: Record<string, TechItem[]> = {}
  for (const tech of techStack) {
    groups[tech.category] = groups[tech.category] ?? []
    groups[tech.category].push(tech)
  }

  const categoryOrder: Array<TechItem['category']> = [
    'language', 'framework', 'ui', 'database', 'tooling', 'deployment', 'testing', 'state',
  ]

  const categoryLabels: Record<string, string> = {
    language:   '语言',
    framework:  '框架',
    ui:         'UI',
    database:   '数据库',
    tooling:    '工具链',
    deployment: '部署',
    testing:    '测试',
    state:      '状态管理',
  }

  const lines: string[] = []
  for (const cat of categoryOrder) {
    if (groups[cat]?.length) {
      const badges = groups[cat].map(makeBadge).join(' ')
      lines.push(`**${categoryLabels[cat]}** &nbsp; ${badges}`)
    }
  }

  return lines.join('  \n')
}

// ─── Main Generator ───────────────────────────────────────────────────────────

export function generateMarkdown(result: AnalysisResult): string {
  const { projectName, projectType, techStack, architectureHighlights, features, complexity, analyzedAt } = result

  const complexityEmoji = { simple: '🟢', medium: '🟡', complex: '🔴' }[complexity]
  const complexityLabel = { simple: '轻量', medium: '中等', complex: '复杂' }[complexity]

  const featuresSection = features
    .map(
      (f, i) => `### ${i + 1}. ${f.icon} ${f.title}

> ${f.description}

${f.relatedFiles.length > 0 ? `**相关文件：** \`${f.relatedFiles.slice(0, 3).join('` · `')}\`` : ''}`,
    )
    .join('\n\n')

  const archSection = architectureHighlights
    .slice(0, 3)
    .map(
      a => `| \`${a.badge}\` | ${a.title} | ${a.description} |`,
    )
    .join('\n')

  const markdown = `<!-- Generated by [Vibe-Lens](https://github.com/citizen204/vibe-lens) -->

## 🔬 项目解析 · ${projectName}

> ${projectType} &nbsp;·&nbsp; ${complexityEmoji} 复杂度：${complexityLabel}

---

### 🧰 技术栈

${groupBadges(techStack)}

---

### 🏗 架构亮点

| 模式 | 特性 | 说明 |
|------|------|------|
${archSection}

---

### ✨ 核心功能

${featuresSection}

---

<sub>Powered by <a href="https://github.com/citizen204/vibe-lens">Vibe-Lens</a> · ${analyzedAt.toLocaleDateString('zh-CN')}</sub>
`

  return markdown.trim()
}

// ─── Plain Text Summary (for preview) ────────────────────────────────────────

export function generatePlainSummary(result: AnalysisResult): string {
  const techNames = result.techStack.slice(0, 8).map(t => t.name).join(' · ')
  const featureNames = result.features.map(f => f.title).join('、')

  return [
    `📦 ${result.projectName}`,
    `${result.projectType}`,
    ``,
    `🧰 技术栈：${techNames}`,
    `🏗 架构：${result.architectureHighlights.map(a => a.badge).join(' / ')}`,
    `✨ 核心功能：${featureNames}`,
  ].join('\n')
}
